config/routes.rb
Rails.application.routes.draw do
  resources :attacks
  resources :reactions
  resources :legendary_actions
  resources :special_abilities
  resources :monsters

  root 'monsters#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/special_ability.rb
class SpecialAbility < ApplicationRecord
    has_and_belongs_to_many :monster
end

app/controllers/special_abilities_controller.rb
class SpecialAbilitiesController < ApplicationController
  before_action :set_special_ability, only: [:show, :edit, :update, :destroy]

  # GET /special_abilities
  # GET /special_abilities.json
  def index
    @special_abilities = SpecialAbility.all
  end

  # GET /special_abilities/1
  # GET /special_abilities/1.json
  def show
  end

  # GET /special_abilities/new
  def new
    @special_ability = SpecialAbility.new
  end

  # GET /special_abilities/1/edit
  def edit
  end

  # POST /special_abilities
  # POST /special_abilities.json
  def create
    @special_ability = SpecialAbility.new(special_ability_params)

    respond_to do |format|
      if @special_ability.save
        format.html { redirect_to @special_ability, notice: 'Special ability was successfully created.' }
        format.json { render :show, status: :created, location: @special_ability }
      else
        format.html { render :new }
        format.json { render json: @special_ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /special_abilities/1
  # PATCH/PUT /special_abilities/1.json
  def update
    respond_to do |format|
      if @special_ability.update(special_ability_params)
        format.html { redirect_to @special_ability, notice: 'Special ability was successfully updated.' }
        format.json { render :show, status: :ok, location: @special_ability }
      else
        format.html { render :edit }
        format.json { render json: @special_ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /special_abilities/1
  # DELETE /special_abilities/1.json
  def destroy
    @special_ability.destroy
    respond_to do |format|
      format.html { redirect_to special_abilities_url, notice: 'Special ability was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_special_ability
      @special_ability = SpecialAbility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def special_ability_params
      params.require(:special_ability).permit(:name, :description, :attack_bonus, :damage_dice)
    end
end

app/helpers/special_abilities_helper.rb
module SpecialAbilitiesHelper
end

app/views/special_abilities/_form.html.erb
<%= form_with(model: special_ability, local: true) do |form| %>
  <% if special_ability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(special_ability.errors.count, "error") %> prohibited this special_ability from being saved:</h2>

      <ul>
      <% special_ability.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label :name %>
  <%= form.text_area :name %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_area :description %>
</div>

<div class="field">
  <%= form.label :attack_bonus %>
  <%= form.number_field :attack_bonus %>
</div>

<div class="field">
  <%= form.label :damage_dice %>
  <%= form.text_area :damage_dice %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/special_abilities/edit.html.erb
<h1>Editing Special Ability</h1>

<%= render 'form', special_ability: @special_ability %>

<%= link_to 'Show', @special_ability %> |
<%= link_to 'Back', special_abilities_path %>

app/views/special_abilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Special Abilities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Attack Bonus</th>
      <th>Damage Dice</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @special_abilities.each do |special_ability| %>
      <tr>
        <td><%= special_ability.name %></td>
        <td><%= special_ability.description %></td>
        <td><%= special_ability.attack_bonus %></td>
        <td><%= special_ability.damage_dice %></td>
        <td><%= link_to 'Show', special_ability %></td>
        <td><%= link_to 'Edit', edit_special_ability_path(special_ability) %></td>
        <td><%= link_to 'Destroy', special_ability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Special Ability', new_special_ability_path %>

app/views/special_abilities/new.html.erb
<h1>New Special Ability</h1>

<%= render 'form', special_ability: @special_ability %>

<%= link_to 'Back', special_abilities_path %>

app/views/special_abilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @special_ability.name %>
</p>

<p>
  <strong>description:</strong>
  <%= @special_ability.description %>
</p>

<p>
  <strong>attack_bonus:</strong>
  <%= @special_ability.attack_bonus %>
</p>

<p>
  <strong>damage_dice:</strong>
  <%= @special_ability.damage_dice %>
</p>

<%= link_to 'Edit', edit_special_ability_path(@special_ability) %> |
<%= link_to 'Back', special_abilities_path %>