config/routes.rb
Rails.application.routes.draw do
  resources :attacks
  resources :reactions
  resources :legendary_actions
  resources :special_abilities
  resources :monsters

  root 'monsters#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/monster.rb
class Monster < ApplicationRecord
    has_and_belongs_to_many :special_ability
    has_and_belongs_to_many :attacks
    has_and_belongs_to_many :legendary_actions
    has_and_belongs_to_many :reactions
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]

  # GET /monsters
  # GET /monsters.json
  def index
    @monsters = Monster.all
  end

  # GET /monsters/1
  # GET /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters
  # POST /monsters.json
  def create
    @monster = Monster.new(monster_params)

    respond_to do |format|
      if @monster.save
        format.html { redirect_to @monster, notice: 'Monster was successfully created.' }
        format.json { render :show, status: :created, location: @monster }
      else
        format.html { render :new }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monsters/1
  # PATCH/PUT /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to @monster, notice: 'Monster was successfully updated.' }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1
  # DELETE /monsters/1.json
  def destroy
    @monster.destroy
    respond_to do |format|
      format.html { redirect_to monsters_url, notice: 'Monster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def rand_Monster
    @monster = Monster.all.sample
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = Monster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monster_params
      params.require(:monster).permit(:name, :size,  :race,  :subtype,  :alignment,  :armor_class,  :hit_points,  :hit_dice,  :speed,  :strength,  :dexterity,  :constitution,  :intelligence,  :wisdom,  :charisma,  :wisdom_save,  :damage_vulnerabilities,  :damage_resistances,  :damage_immunities,  :condition_immunities,  :senses,  :languages,  :challenge_rating,  :constitution_save,  :perception,  :history,  :intelligence_save,  :religion,  :medicine,  :stealth,  :dexterity_save,  :charisma_save,  :persuasion,  :insight,  :deception,  :athletics,  :arcana,  :nature,  :acrobatics,  :strength_save,  :survival,  :investigation,  :intimidation,  :performance )
    end
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/monsters/_form.html.erb
<%= form_with(model: monster, local: true) do |form| %>
  <% if monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
      <% monster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% monster.attributes.each do |key, value| %>
    <tr>
      <% if value == monster.id -%>
      <% %>
      <% else %>
        <td><%= form.label key %></td>
        <td><%= form.text_area key, :value => value%> </td>
      <%end%>
    </tr>
  <%end%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/monsters/edit.html.erb
<h1>Editing Monster</h1>

<%= render 'form', monster: @monster %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

app/views/monsters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Monsters</h1>

  <table border="2">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Race</th>
      <th>Subtype</th>
      <th>AC</th>
      <th>HP</th>
      <th>Hit Dice</th>
      <th>Challenge Rating</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @monsters.each do |monster| %>
      <tr>
        <td><%= monster.id %></td>
        <td><%= monster.name %></td>
        <td><%= monster.race %></td>
        <td><%= monster.subtype %></td>
        <td><%= monster.armor_class %></td>
        <td><%= monster.hit_points %></td>
        <td><%= monster.hit_dice %></td>
        <td><%= monster.challenge_rating %></td>
        <td><%= link_to 'Show', monster %></td>
        <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
        <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
<hr>
<h1>Random Monster</h1>
  <td><%= Monster.all.sample.name %></td>
<br>
<hr>
<%= link_to 'New Monster', new_monster_path %>

app/views/monsters/new.html.erb
<h1>New Monster</h1>

<%= render 'form', monster: @monster %>

<%= link_to 'Back', monsters_path %>

app/views/monsters/show.html.erb
<p id="notice"><%= notice %></p>


<% @monster.attributes.each do |key, value| %>
  <tr>
    <% if value == @monster.id -%>
     <% %>
    <% else %>
      <p><strong><%=key%></strong></td>
      <p><%=value%></td>
    <%end%>
  </tr>
<%end%>


___<br>
>## <%= @monster.name %><br>
>*<%= @monster.race%>, <%= @monster.alignment%>*<br>
> ___<br>
> - **Armor Class** <%= @monster.armor_class%><br>
> - **Hit Points** <%= @monster.hit_points%> (<%= @monster.hit_dice%>)<br>
> - **Speed** <%= @monster.speed%><br>
>___<br>
>|STR|DEX|CON|INT|WIS|CHA|<br>
>|:---:|:---:|:---:|:---:|:---:|:---:|<br>
>|<%= @monster.strength.to_i%> (<%=@monster.strength%>)
|<%= @monster.dexterity.to_i%> (<%= @monster.dexterity%>)
|<%= @monster.constitution.to_i%> (<%= @monster.constitution%>)
|<%= @monster.intelligence.to_i%> (<%= @monster.intelligence%>)
|<%= @monster.wisdom.to_i%> (<%= @monster.wisdom%>)
|<%= @monster.charisma.to_i%> (<%= @monster.charisma%>)
|<br>
>___<br>
> - **Damage Vulnerabilities** <%= @monster.damage_vulnerabilities%><br>
> - **Damage Resistances** <%= @monster.damage_resistances%><br>
> - **Damage Immunities** <%= @monster.damage_immunities%><br>
> - **Condition Immunities** <%= @monster.condition_immunities%><br>
> - **Senses** <%= @monster.senses %> <br>
> - **Languages** <%= @monster.languages %> <br>
> - **Challenge Rating** <%= @monster.challenge_rating %> <br>
> ___<br>
<% @monster.special_ability.ids.each do |x|%><br>
> ***<%= @monster.special_ability.find(x).name%>***<br>
<%= @monster.special_ability.find(x).description%><br>
<%end%>
><br>
> ### Actions<br>
> ___<br>
<% @monster.attacks.ids.each do |x|%><br>
> ***<%= @monster.attacks.find(x).name%>***<br>
<%= @monster.attacks.find(x).description%><br>
<%end%>
><br>
> ### Reactions<br>
> ___<br>
<% @monster.reactions.ids.each do |x|%><br>
> ***<%= @monster.reactions.find(x).name%>***<br>
<%= @monster.reactions.find(x).description%><br>
<%end%>
><br>
<hr>


<a href="http://homebrewery.naturalcrit.com/">Copy the above text and paste it to this website!</a>

<hr>

<%= link_to 'Edit', edit_monster_path(@monster) %> |
<%= link_to 'Back', monsters_path %>