config/routes.rb
Rails.application.routes.draw do
  resources :attacks
  resources :reactions
  resources :legendary_actions
  resources :special_abilities
  resources :monsters

  root 'monsters#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attack.rb
class Attack < ApplicationRecord
    has_and_belongs_to_many :monsters
end

app/controllers/attacks_controller.rb
class AttacksController < ApplicationController
  before_action :set_attack, only: [:show, :edit, :update, :destroy]

  # GET /attacks
  # GET /attacks.json
  def index
    @attacks = Attack.all
  end

  # GET /attacks/1
  # GET /attacks/1.json
  def show
  end

  # GET /attacks/new
  def new
    @attack = Attack.new
  end

  # GET /attacks/1/edit
  def edit
  end

  # POST /attacks
  # POST /attacks.json
  def create
    @attack = Attack.new(attack_params)

    respond_to do |format|
      if @attack.save
        format.html { redirect_to @attack, notice: 'Attack was successfully created.' }
        format.json { render :show, status: :created, location: @attack }
      else
        format.html { render :new }
        format.json { render json: @attack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attacks/1
  # PATCH/PUT /attacks/1.json
  def update
    respond_to do |format|
      if @attack.update(attack_params)
        format.html { redirect_to @attack, notice: 'Attack was successfully updated.' }
        format.json { render :show, status: :ok, location: @attack }
      else
        format.html { render :edit }
        format.json { render json: @attack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attacks/1
  # DELETE /attacks/1.json
  def destroy
    @attack.destroy
    respond_to do |format|
      format.html { redirect_to attacks_url, notice: 'Attack was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attack
      @attack = Attack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attack_params
      params.require(:attack).permit(:name, :description, :damage_dice, :damage_bonus)
    end
end

app/helpers/attacks_helper.rb
module AttacksHelper
end

app/views/attacks/_form.html.erb
<%= form_with(model: attack, local: true) do |form| %>
  <% if attack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attack.errors.count, "error") %> prohibited this attack from being saved:</h2>

      <ul>
      <% attack.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :damage_dice %>
    <%= form.text_field :damage_dice %>
  </div>

  <div class="field">
    <%= form.label :damage_bonus %>
    <%= form.number_field :damage_bonus %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attacks/edit.html.erb
<h1>Editing Attack</h1>

<%= render 'form', attack: @attack %>

<%= link_to 'Show', @attack %> |
<%= link_to 'Back', attacks_path %>

app/views/attacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attacks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Damage dice</th>
      <th>Damage bonus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attacks.each do |attack| %>
      <tr>
        <td><%= attack.name %></td>
        <td><%= attack.description %></td>
        <td><%= attack.damage_dice %></td>
        <td><%= attack.damage_bonus %></td>
        <td><%= link_to 'Show', attack %></td>
        <td><%= link_to 'Edit', edit_attack_path(attack) %></td>
        <td><%= link_to 'Destroy', attack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attack', new_attack_path %>

app/views/attacks/new.html.erb
<h1>New Attack</h1>

<%= render 'form', attack: @attack %>

<%= link_to 'Back', attacks_path %>

app/views/attacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attack.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @attack.description %>
</p>

<p>
  <strong>Damage dice:</strong>
  <%= @attack.damage_dice %>
</p>

<p>
  <strong>Damage bonus:</strong>
  <%= @attack.damage_bonus %>
</p>

<%= link_to 'Edit', edit_attack_path(@attack) %> |
<%= link_to 'Back', attacks_path %>