config/routes.rb
Rails.application.routes.draw do
  resources :attacks
  resources :reactions
  resources :legendary_actions
  resources :special_abilities
  resources :monsters

  root 'monsters#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :set_reaction, only: [:show, :edit, :update, :destroy]

  # GET /reactions
  # GET /reactions.json
  def index
    @reactions = Reaction.all
  end

  # GET /reactions/1
  # GET /reactions/1.json
  def show
  end

  # GET /reactions/new
  def new
    @reaction = Reaction.new
  end

  # GET /reactions/1/edit
  def edit
  end

  # POST /reactions
  # POST /reactions.json
  def create
    @reaction = Reaction.new(reaction_params)

    respond_to do |format|
      if @reaction.save
        format.html { redirect_to @reaction, notice: 'Reaction was successfully created.' }
        format.json { render :show, status: :created, location: @reaction }
      else
        format.html { render :new }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reactions/1
  # PATCH/PUT /reactions/1.json
  def update
    respond_to do |format|
      if @reaction.update(reaction_params)
        format.html { redirect_to @reaction, notice: 'Reaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @reaction }
      else
        format.html { render :edit }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reactions/1
  # DELETE /reactions/1.json
  def destroy
    @reaction.destroy
    respond_to do |format|
      format.html { redirect_to reactions_url, notice: 'Reaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reaction
      @reaction = Reaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reaction_params
      params.require(:reaction).permit(:name, :description, :attack_bonus)
    end
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/reactions/_form.html.erb
<%= form_with(model: reaction, local: true) do |form| %>
  <% if reaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reaction.errors.count, "error") %> prohibited this reaction from being saved:</h2>

      <ul>
      <% reaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :attack_bonus %>
    <%= form.number_field :attack_bonus %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reactions/edit.html.erb
<h1>Editing Reaction</h1>

<%= render 'form', reaction: @reaction %>

<%= link_to 'Show', @reaction %> |
<%= link_to 'Back', reactions_path %>

app/views/reactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reactions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Attack bonus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reactions.each do |reaction| %>
      <tr>
        <td><%= reaction.name %></td>
        <td><%= reaction.description %></td>
        <td><%= reaction.attack_bonus %></td>
        <td><%= link_to 'Show', reaction %></td>
        <td><%= link_to 'Edit', edit_reaction_path(reaction) %></td>
        <td><%= link_to 'Destroy', reaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reaction', new_reaction_path %>

app/views/reactions/new.html.erb
<h1>New Reaction</h1>

<%= render 'form', reaction: @reaction %>

<%= link_to 'Back', reactions_path %>

app/views/reactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reaction.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @reaction.description %>
</p>

<p>
  <strong>Attack bonus:</strong>
  <%= @reaction.attack_bonus %>
</p>

<%= link_to 'Edit', edit_reaction_path(@reaction) %> |
<%= link_to 'Back', reactions_path %>